### PR TITLE
fix: added check for empty strings in response

### PR DESCRIPTION
**Pull request by MeganJBlevins**
This fix removes unnecessary console errors created by parsing the response string. It filters the split string to remove any empty strings from being included in the loop to process the response data. 

Note: this is a PR into Main as I branched from main, which seems to have more commits/content. Be sure to change to Dev for testing/if necessary.

### CODE REVIEW

**Comment by MeganJBlevins** [comment]
@Bukashk0zzz - I know this isn't a fix that resolves any real issues, but my client is insistent that the error is gone before I can implement it. Do you think this is something that can be added sometime soon? Whether it's this or another fix makes no difference to me! Thanks a bunch!

**Comment by Bukashk0zzz** [comment]
Hi @MeganJBlevins 
Thanks for the request.
Sorry for the delay in reviewing it.

We will discuss this internally today and provide you with feedback.
The issue is that this change requires releasing a new version of drag.js on our CDN.

**Comment by Bukashk0zzz** [comment]
We will merge this request until end of this week and provide new release of Data Tag. 
Thanks for pointing on this issue.

**Comment by MeganJBlevins** [comment]
@Bukashk0zzz Thank you!

**Review by kHorozhanov — APPROVED** [review]

**Comment by kHorozhanov** [comment]
Hi @MeganJBlevins, the changes have already been published to our CDN and will be available through the same URL https://cdn.stape.io/dtag/v7.js, so there's no need to update your existing setup. Thank you!

**Pull request merged**
